import { Aisle } from './aisles';

/**
 * Mots-clés anglais. Voir `keywords.ts` pour le dictionnaire assemblé.
 *
 * Le compilateur de motifs tolère un `s` ou un `x` final sur chaque mot, ce
 * qui couvre les pluriels réguliers. Les pluriels irréguliers fréquents
 * (`tomatoes`, `cherries`) ont donc leur propre entrée : sans elle, taper
 * l'article au pluriel — le cas normal sur une liste de courses — ne
 * proposerait rien.
 */
export const KEYWORDS_EN: ReadonlyArray<readonly [string, Aisle, string]> = [
  // Fruit & vegetables
  ['apple', 'fruits-legumes', '🍎'],
  ['pear', 'fruits-legumes', '🍐'],
  ['banana', 'fruits-legumes', '🍌'],
  ['clementine', 'fruits-legumes', '🍊'],
  ['tangerine', 'fruits-legumes', '🍊'],
  ['lemon', 'fruits-legumes', '🍋'],
  ['lime', 'fruits-legumes', '🍋'],
  ['strawberry', 'fruits-legumes', '🍓'],
  ['strawberries', 'fruits-legumes', '🍓'],
  ['raspberry', 'fruits-legumes', '🍓'],
  ['raspberries', 'fruits-legumes', '🍓'],
  ['blueberry', 'fruits-legumes', '🫐'],
  ['blueberries', 'fruits-legumes', '🫐'],
  ['grape', 'fruits-legumes', '🍇'],
  ['peach', 'fruits-legumes', '🍑'],
  ['peaches', 'fruits-legumes', '🍑'],
  ['apricot', 'fruits-legumes', '🍑'],
  ['cherry', 'fruits-legumes', '🍒'],
  ['cherries', 'fruits-legumes', '🍒'],
  ['pineapple', 'fruits-legumes', '🍍'],
  ['mango', 'fruits-legumes', '🥭'],
  ['watermelon', 'fruits-legumes', '🍉'],
  ['avocado', 'fruits-legumes', '🥑'],
  ['tomato', 'fruits-legumes', '🍅'],
  ['tomatoes', 'fruits-legumes', '🍅'],
  ['carrot', 'fruits-legumes', '🥕'],
  ['potato', 'fruits-legumes', '🥔'],
  ['potatoes', 'fruits-legumes', '🥔'],
  ['onion', 'fruits-legumes', '🧅'],
  ['shallot', 'fruits-legumes', '🧅'],
  ['garlic', 'fruits-legumes', '🧄'],
  ['leek', 'fruits-legumes', '🥬'],
  ['lettuce', 'fruits-legumes', '🥬'],
  ['salad', 'fruits-legumes', '🥬'],
  ['spinach', 'fruits-legumes', '🥬'],
  ['cabbage', 'fruits-legumes', '🥬'],
  ['kale', 'fruits-legumes', '🥬'],
  ['broccoli', 'fruits-legumes', '🥦'],
  ['zucchini', 'fruits-legumes', '🥒'],
  ['cucumber', 'fruits-legumes', '🥒'],
  ['eggplant', 'fruits-legumes', '🍆'],
  // Deux mots, donc plus spécifique que « pepper » l'épice : c'est bien le
  // légume qui l'emporte quand les deux pourraient correspondre.
  ['bell pepper', 'fruits-legumes', '🫑'],
  ['mushroom', 'fruits-legumes', '🍄'],
  ['green bean', 'fruits-legumes', '🫘'],
  ['pea', 'fruits-legumes', '🫛'],
  ['sweetcorn', 'fruits-legumes', '🌽'],
  ['radish', 'fruits-legumes', '🥗'],
  ['radishes', 'fruits-legumes', '🥗'],
  ['beetroot', 'fruits-legumes', '🥗'],
  ['turnip', 'fruits-legumes', '🥗'],
  ['pumpkin', 'fruits-legumes', '🎃'],
  ['squash', 'fruits-legumes', '🎃'],
  ['parsley', 'fruits-legumes', '🌿'],
  ['basil', 'fruits-legumes', '🌿'],
  ['cilantro', 'fruits-legumes', '🌿'],
  ['mint', 'fruits-legumes', '🌿'],

  // Butcher
  ['beef', 'boucherie', '🥩'],
  ['meat', 'boucherie', '🥩'],
  ['mince', 'boucherie', '🥩'],
  ['veal', 'boucherie', '🥩'],
  ['lamb', 'boucherie', '🍖'],
  ['pork', 'boucherie', '🥓'],
  ['ham', 'boucherie', '🍖'],
  ['sausage', 'boucherie', '🌭'],
  ['salami', 'boucherie', '🍖'],
  ['chicken', 'boucherie', '🍗'],
  ['turkey', 'boucherie', '🍗'],
  ['poultry', 'boucherie', '🍗'],

  // Fishmonger
  ['fish', 'poissonnerie', '🐟'],
  ['salmon', 'poissonnerie', '🐟'],
  ['cod', 'poissonnerie', '🐟'],
  ['trout', 'poissonnerie', '🐟'],
  ['tuna', 'poissonnerie', '🐟'],
  ['mackerel', 'poissonnerie', '🐟'],
  ['prawn', 'poissonnerie', '🦐'],
  ['shrimp', 'poissonnerie', '🦐'],
  ['mussel', 'poissonnerie', '🦪'],
  ['oyster', 'poissonnerie', '🦪'],
  ['crab', 'poissonnerie', '🦀'],
  ['squid', 'poissonnerie', '🦑'],

  // Dairy
  ['milk', 'cremerie', '🥛'],
  ['butter', 'cremerie', '🧈'],
  ['cream', 'cremerie', '🥛'],
  ['yogurt', 'cremerie', '🥛'],
  ['yoghurt', 'cremerie', '🥛'],
  ['cheese', 'cremerie', '🧀'],
  ['cheddar', 'cremerie', '🧀'],
  ['goat cheese', 'cremerie', '🧀'],
  ['egg', 'cremerie', '🥚'],
  ['cottage cheese', 'cremerie', '🥛'],

  // Bakery
  ['bread', 'boulangerie', '🥖'],
  ['loaf', 'boulangerie', '🍞'],
  ['bun', 'boulangerie', '🍞'],
  ['pastry', 'boulangerie', '🥐'],
  ['pastries', 'boulangerie', '🥐'],
  ['pitta', 'boulangerie', '🫓'],

  // Savoury groceries
  ['pasta', 'epicerie-salee', '🍝'],
  ['noodle', 'epicerie-salee', '🍝'],
  ['rice', 'epicerie-salee', '🍚'],
  ['couscous', 'epicerie-salee', '🌾'],
  ['bulgur', 'epicerie-salee', '🌾'],
  ['lentil', 'epicerie-salee', '🫘'],
  ['chickpea', 'epicerie-salee', '🫘'],
  ['oil', 'epicerie-salee', '🫒'],
  ['vinegar', 'epicerie-salee', '🧴'],
  ['salt', 'epicerie-salee', '🧂'],
  ['pepper', 'epicerie-salee', '🧂'],
  ['spice', 'epicerie-salee', '🧂'],
  ['mustard', 'epicerie-salee', '🥫'],
  ['tinned', 'epicerie-salee', '🥫'],
  ['canned', 'epicerie-salee', '🥫'],
  ['soup', 'epicerie-salee', '🍲'],
  ['stock cube', 'epicerie-salee', '🍲'],
  ['flour', 'epicerie-salee', '🌾'],
  ['yeast', 'epicerie-salee', '🌾'],
  ['crisps', 'epicerie-salee', '🍟'],
  ['pretzel', 'epicerie-salee', '🥨'],
  ['peanut', 'epicerie-salee', '🥜'],

  // Sweet groceries
  ['sugar', 'epicerie-sucree', '🍬'],
  ['honey', 'epicerie-sucree', '🍯'],
  ['jam', 'epicerie-sucree', '🍯'],
  ['chocolate', 'epicerie-sucree', '🍫'],
  ['cookie', 'epicerie-sucree', '🍪'],
  ['cake', 'epicerie-sucree', '🍰'],
  ['sweets', 'epicerie-sucree', '🍬'],
  ['candy', 'epicerie-sucree', '🍬'],
  ['cereal', 'epicerie-sucree', '🥣'],
  ['oats', 'epicerie-sucree', '🥣'],
  ['porridge', 'epicerie-sucree', '🥣'],
  ['applesauce', 'epicerie-sucree', '🍎'],
  ['almond', 'epicerie-sucree', '🌰'],
  ['walnut', 'epicerie-sucree', '🌰'],
  ['hazelnut', 'epicerie-sucree', '🌰'],

  // Drinks
  ['water', 'boissons', '💧'],
  ['juice', 'boissons', '🧃'],
  ['squash drink', 'boissons', '🧃'],
  ['lemonade', 'boissons', '🥤'],
  ['beer', 'boissons', '🍺'],
  ['wine', 'boissons', '🍷'],
  ['cider', 'boissons', '🍺'],
  ['coffee', 'boissons', '☕'],
  ['tea', 'boissons', '🍵'],
  ['herbal tea', 'boissons', '🍵'],
  ['cocoa', 'boissons', '🍫'],

  // Frozen
  ['frozen', 'surgeles', '🧊'],
  ['ice cream', 'surgeles', '🍦'],
  ['fries', 'surgeles', '🍟'],
  ['ice cube', 'surgeles', '🧊'],

  // Toiletries
  ['soap', 'hygiene', '🧼'],
  ['shower gel', 'hygiene', '🧴'],
  ['shampoo', 'hygiene', '🧴'],
  ['conditioner', 'hygiene', '🧴'],
  ['toothpaste', 'hygiene', '🪥'],
  ['toothbrush', 'hygiene', '🪥'],
  ['deodorant', 'hygiene', '🧴'],
  ['razor', 'hygiene', '🪒'],
  ['shaving foam', 'hygiene', '🧴'],
  ['cotton pad', 'hygiene', '🧻'],
  ['toilet paper', 'hygiene', '🧻'],
  ['toilet roll', 'hygiene', '🧻'],
  ['tissue', 'hygiene', '🤧'],
  ['sanitary pad', 'hygiene', '🧴'],
  ['sunscreen', 'hygiene', '🧴'],

  // Pharmacy
  ['medicine', 'pharmacie', '💊'],
  ['medication', 'pharmacie', '💊'],
  ['painkiller', 'pharmacie', '💊'],
  ['paracetamol', 'pharmacie', '💊'],
  ['ibuprofen', 'pharmacie', '💊'],
  ['aspirin', 'pharmacie', '💊'],
  ['vitamin', 'pharmacie', '💊'],
  ['throat lozenge', 'pharmacie', '💊'],
  ['cough syrup', 'pharmacie', '💊'],
  ['plaster', 'pharmacie', '🩹'],
  ['band aid', 'pharmacie', '🩹'],
  ['bandage', 'pharmacie', '🩹'],
  ['antiseptic', 'pharmacie', '🧴'],
  ['saline solution', 'pharmacie', '💧'],
  ['nasal spray', 'pharmacie', '💧'],
  ['thermometer', 'pharmacie', '🌡️'],
  ['face mask', 'pharmacie', '😷'],
  ['hand sanitiser', 'pharmacie', '🧴'],
  ['hand sanitizer', 'pharmacie', '🧴'],
  ['condom', 'pharmacie', '💊'],

  // Household
  ['laundry', 'entretien', '🧺'],
  ['detergent', 'entretien', '🧺'],
  ['fabric softener', 'entretien', '🧺'],
  ['washing up liquid', 'entretien', '🧽'],
  ['dishwasher tablet', 'entretien', '🧽'],
  ['sponge', 'entretien', '🧽'],
  ['cleaner', 'entretien', '🧴'],
  ['bleach', 'entretien', '🧴'],
  ['bin bag', 'entretien', '🗑️'],
  ['bin liner', 'entretien', '🗑️'],
  ['kitchen roll', 'entretien', '🧻'],
  ['paper towel', 'entretien', '🧻'],
  ['tin foil', 'entretien', '🧻'],
  ['aluminium foil', 'entretien', '🧻'],
  ['cling film', 'entretien', '🧻'],
  ['battery', 'entretien', '🔋'],
  ['batteries', 'entretien', '🔋'],
  ['light bulb', 'entretien', '💡'],
  ['match', 'entretien', '🔥'],
  ['matches', 'entretien', '🔥'],
  ['candle', 'entretien', '🕯️'],

  // Baby
  ['nappy', 'bebe', '🍼'],
  ['nappies', 'bebe', '🍼'],
  ['diaper', 'bebe', '🍼'],
  ['baby wipe', 'bebe', '🍼'],
  ['baby food', 'bebe', '🍼'],
  ['baby bottle', 'bebe', '🍼'],
  ['formula', 'bebe', '🍼'],

  // Pets
  ['kibble', 'animaux', '🐾'],
  ['cat litter', 'animaux', '🐾'],
  ['cat food', 'animaux', '🐱'],
  ['dog food', 'animaux', '🐶'],
  ['pet food', 'animaux', '🐾'],

  // Books & stationery
  ['book', 'librairie', '📚'],
  ['novel', 'librairie', '📚'],
  ['comic', 'librairie', '📚'],
  ['magazine', 'librairie', '📰'],
  ['newspaper', 'librairie', '📰'],
  ['notebook', 'librairie', '📓'],
  ['diary', 'librairie', '📓'],
  ['folder', 'librairie', '🗂️'],
  ['pen', 'librairie', '🖊️'],
  ['pencil', 'librairie', '✏️'],
  ['marker', 'librairie', '🖍️'],
  ['highlighter', 'librairie', '🖍️'],
  ['eraser', 'librairie', '✏️'],
  ['ruler', 'librairie', '📏'],
  ['scissors', 'librairie', '✂️'],
  ['glue', 'librairie', '🖇️'],
  ['pencil case', 'librairie', '✏️'],
  ['calculator', 'librairie', '🧮'],
  ['envelope', 'librairie', '✉️'],
  ['stamp', 'librairie', '📮'],
  ['postcard', 'librairie', '📮'],
  ['wrapping paper', 'librairie', '🎁'],
  ['ink cartridge', 'librairie', '🖨️'],

  // Multimedia
  ['cable', 'multimedia', '🔌'],
  ['charger', 'multimedia', '🔌'],
  ['extension lead', 'multimedia', '🔌'],
  ['adapter', 'multimedia', '🔌'],
  ['power bank', 'multimedia', '🔋'],
  ['earphone', 'multimedia', '🎧'],
  ['headphone', 'multimedia', '🎧'],
  ['speaker', 'multimedia', '🔊'],
  ['usb stick', 'multimedia', '💾'],
  ['memory card', 'multimedia', '💾'],
  ['mouse', 'multimedia', '🖱️'],
  ['keyboard', 'multimedia', '⌨️'],
  ['screen', 'multimedia', '🖥️'],
  ['television', 'multimedia', '📺'],
  ['controller', 'multimedia', '🎮'],
  ['video game', 'multimedia', '🎮'],
  ['dvd', 'multimedia', '📀'],
  ['blu ray', 'multimedia', '📀'],
];
