import { Aisle } from './aisles';

/**
 * Mots-clés français. Voir `keywords.ts` pour le dictionnaire assemblé.
 *
 * Les clés sont normalisées (minuscules, sans accents) — voir `normalize()`.
 * La correspondance se fait sur le mot entier ou le début d'un mot du libellé,
 * jamais sur une sous-chaîne quelconque : « ail » ne doit pas capter « volaille ».
 */
export const KEYWORDS_FR: ReadonlyArray<readonly [string, Aisle, string]> = [
  // Fruits & légumes
  ['pomme', 'fruits-legumes', '🍎'],
  ['poire', 'fruits-legumes', '🍐'],
  ['banane', 'fruits-legumes', '🍌'],
  ['orange', 'fruits-legumes', '🍊'],
  ['clementine', 'fruits-legumes', '🍊'],
  ['mandarine', 'fruits-legumes', '🍊'],
  ['citron', 'fruits-legumes', '🍋'],
  ['fraise', 'fruits-legumes', '🍓'],
  ['framboise', 'fruits-legumes', '🍓'],
  ['myrtille', 'fruits-legumes', '🫐'],
  ['raisin', 'fruits-legumes', '🍇'],
  ['peche', 'fruits-legumes', '🍑'],
  ['abricot', 'fruits-legumes', '🍑'],
  ['cerise', 'fruits-legumes', '🍒'],
  ['ananas', 'fruits-legumes', '🍍'],
  ['mangue', 'fruits-legumes', '🥭'],
  ['kiwi', 'fruits-legumes', '🥝'],
  ['melon', 'fruits-legumes', '🍈'],
  ['pasteque', 'fruits-legumes', '🍉'],
  ['avocat', 'fruits-legumes', '🥑'],
  ['tomate', 'fruits-legumes', '🍅'],
  ['carotte', 'fruits-legumes', '🥕'],
  ['pomme de terre', 'fruits-legumes', '🥔'],
  ['patate', 'fruits-legumes', '🥔'],
  ['oignon', 'fruits-legumes', '🧅'],
  ['echalote', 'fruits-legumes', '🧅'],
  ['ail', 'fruits-legumes', '🧄'],
  ['poireau', 'fruits-legumes', '🥬'],
  ['salade', 'fruits-legumes', '🥬'],
  ['laitue', 'fruits-legumes', '🥬'],
  ['epinard', 'fruits-legumes', '🥬'],
  ['chou', 'fruits-legumes', '🥬'],
  ['brocoli', 'fruits-legumes', '🥦'],
  ['courgette', 'fruits-legumes', '🥒'],
  ['concombre', 'fruits-legumes', '🥒'],
  ['aubergine', 'fruits-legumes', '🍆'],
  ['poivron', 'fruits-legumes', '🫑'],
  ['champignon', 'fruits-legumes', '🍄'],
  ['haricot', 'fruits-legumes', '🫘'],
  ['petit pois', 'fruits-legumes', '🫛'],
  ['mais', 'fruits-legumes', '🌽'],
  ['radis', 'fruits-legumes', '🥗'],
  ['betterave', 'fruits-legumes', '🥗'],
  ['navet', 'fruits-legumes', '🥗'],
  ['courge', 'fruits-legumes', '🎃'],
  ['potiron', 'fruits-legumes', '🎃'],
  ['persil', 'fruits-legumes', '🌿'],
  ['basilic', 'fruits-legumes', '🌿'],
  ['coriandre', 'fruits-legumes', '🌿'],
  ['menthe', 'fruits-legumes', '🌿'],
  ['herbe', 'fruits-legumes', '🌿'],

  // Boucherie
  ['boeuf', 'boucherie', '🥩'],
  ['steak', 'boucherie', '🥩'],
  ['entrecote', 'boucherie', '🥩'],
  ['viande', 'boucherie', '🥩'],
  ['veau', 'boucherie', '🥩'],
  ['agneau', 'boucherie', '🍖'],
  ['porc', 'boucherie', '🥓'],
  ['lard', 'boucherie', '🥓'],
  ['bacon', 'boucherie', '🥓'],
  ['jambon', 'boucherie', '🍖'],
  ['saucisse', 'boucherie', '🌭'],
  ['saucisson', 'boucherie', '🍖'],
  ['chorizo', 'boucherie', '🍖'],
  ['poulet', 'boucherie', '🍗'],
  ['dinde', 'boucherie', '🍗'],
  ['canard', 'boucherie', '🍗'],
  ['volaille', 'boucherie', '🍗'],
  ['escalope', 'boucherie', '🍗'],
  ['merguez', 'boucherie', '🌭'],
  ['pate', 'boucherie', '🍖'],
  ['rillette', 'boucherie', '🍖'],

  // Poissonnerie
  ['poisson', 'poissonnerie', '🐟'],
  ['saumon', 'poissonnerie', '🐟'],
  ['cabillaud', 'poissonnerie', '🐟'],
  ['colin', 'poissonnerie', '🐟'],
  ['truite', 'poissonnerie', '🐟'],
  ['thon', 'poissonnerie', '🐟'],
  ['sardine', 'poissonnerie', '🐟'],
  ['maquereau', 'poissonnerie', '🐟'],
  ['crevette', 'poissonnerie', '🦐'],
  ['gambas', 'poissonnerie', '🦐'],
  ['moule', 'poissonnerie', '🦪'],
  ['huitre', 'poissonnerie', '🦪'],
  ['crabe', 'poissonnerie', '🦀'],
  ['calamar', 'poissonnerie', '🦑'],
  ['surimi', 'poissonnerie', '🍥'],

  // Crèmerie
  ['lait', 'cremerie', '🥛'],
  ['beurre', 'cremerie', '🧈'],
  ['creme', 'cremerie', '🥛'],
  ['yaourt', 'cremerie', '🥛'],
  ['yaourts', 'cremerie', '🥛'],
  ['fromage', 'cremerie', '🧀'],
  ['comte', 'cremerie', '🧀'],
  ['gruyere', 'cremerie', '🧀'],
  ['emmental', 'cremerie', '🧀'],
  ['camembert', 'cremerie', '🧀'],
  ['chevre', 'cremerie', '🧀'],
  ['mozzarella', 'cremerie', '🧀'],
  ['parmesan', 'cremerie', '🧀'],
  ['raclette', 'cremerie', '🧀'],
  ['oeuf', 'cremerie', '🥚'],
  ['oeufs', 'cremerie', '🥚'],
  ['fromage blanc', 'cremerie', '🥛'],
  ['petit suisse', 'cremerie', '🥛'],
  ['skyr', 'cremerie', '🥛'],

  // Boulangerie
  ['pain', 'boulangerie', '🥖'],
  ['baguette', 'boulangerie', '🥖'],
  ['brioche', 'boulangerie', '🍞'],
  ['croissant', 'boulangerie', '🥐'],
  ['pain au chocolat', 'boulangerie', '🥐'],
  ['viennoiserie', 'boulangerie', '🥐'],
  ['bagel', 'boulangerie', '🥯'],
  ['tortilla', 'boulangerie', '🫓'],
  ['wrap', 'boulangerie', '🫓'],

  // Épicerie salée
  ['pates', 'epicerie-salee', '🍝'],
  ['spaghetti', 'epicerie-salee', '🍝'],
  ['tagliatelle', 'epicerie-salee', '🍝'],
  ['penne', 'epicerie-salee', '🍝'],
  ['lasagne', 'epicerie-salee', '🍝'],
  ['riz', 'epicerie-salee', '🍚'],
  ['quinoa', 'epicerie-salee', '🌾'],
  ['semoule', 'epicerie-salee', '🌾'],
  ['couscous', 'epicerie-salee', '🌾'],
  ['boulgour', 'epicerie-salee', '🌾'],
  ['lentille', 'epicerie-salee', '🫘'],
  ['pois chiche', 'epicerie-salee', '🫘'],
  ['huile', 'epicerie-salee', '🫒'],
  ['olive', 'epicerie-salee', '🫒'],
  ['vinaigre', 'epicerie-salee', '🧴'],
  ['sel', 'epicerie-salee', '🧂'],
  ['poivre', 'epicerie-salee', '🧂'],
  ['epice', 'epicerie-salee', '🧂'],
  ['moutarde', 'epicerie-salee', '🥫'],
  ['ketchup', 'epicerie-salee', '🥫'],
  ['mayonnaise', 'epicerie-salee', '🥫'],
  ['sauce', 'epicerie-salee', '🥫'],
  ['conserve', 'epicerie-salee', '🥫'],
  ['soupe', 'epicerie-salee', '🍲'],
  ['bouillon', 'epicerie-salee', '🍲'],
  ['farine', 'epicerie-salee', '🌾'],
  ['levure', 'epicerie-salee', '🌾'],
  ['chips', 'epicerie-salee', '🍟'],
  ['apero', 'epicerie-salee', '🥨'],
  ['biscuit apero', 'epicerie-salee', '🥨'],
  ['cacahuete', 'epicerie-salee', '🥜'],
  ['pizza', 'epicerie-salee', '🍕'],

  // Épicerie sucrée
  ['sucre', 'epicerie-sucree', '🍬'],
  ['miel', 'epicerie-sucree', '🍯'],
  ['confiture', 'epicerie-sucree', '🍯'],
  ['chocolat', 'epicerie-sucree', '🍫'],
  ['biscuit', 'epicerie-sucree', '🍪'],
  ['gateau', 'epicerie-sucree', '🍰'],
  ['bonbon', 'epicerie-sucree', '🍬'],
  ['cereale', 'epicerie-sucree', '🥣'],
  ['muesli', 'epicerie-sucree', '🥣'],
  ['compote', 'epicerie-sucree', '🍎'],
  ['nutella', 'epicerie-sucree', '🍫'],
  ['pate a tartiner', 'epicerie-sucree', '🍫'],
  ['amande', 'epicerie-sucree', '🌰'],
  ['noix', 'epicerie-sucree', '🌰'],
  ['noisette', 'epicerie-sucree', '🌰'],

  // Boissons
  ['eau', 'boissons', '💧'],
  ['jus', 'boissons', '🧃'],
  ['soda', 'boissons', '🥤'],
  ['coca', 'boissons', '🥤'],
  ['limonade', 'boissons', '🥤'],
  ['sirop', 'boissons', '🧃'],
  ['biere', 'boissons', '🍺'],
  ['vin', 'boissons', '🍷'],
  ['champagne', 'boissons', '🍾'],
  ['cidre', 'boissons', '🍺'],
  ['cafe', 'boissons', '☕'],
  ['the', 'boissons', '🍵'],
  ['infusion', 'boissons', '🍵'],
  ['tisane', 'boissons', '🍵'],
  ['chocolat en poudre', 'boissons', '🍫'],

  // Surgelés
  ['surgele', 'surgeles', '🧊'],
  ['glace', 'surgeles', '🍦'],
  ['sorbet', 'surgeles', '🍨'],
  ['frite', 'surgeles', '🍟'],
  ['glacon', 'surgeles', '🧊'],
  ['nugget', 'surgeles', '🍗'],

  // Hygiène
  ['savon', 'hygiene', '🧼'],
  ['gel douche', 'hygiene', '🧴'],
  ['shampoing', 'hygiene', '🧴'],
  ['apres-shampoing', 'hygiene', '🧴'],
  ['dentifrice', 'hygiene', '🪥'],
  ['brosse a dent', 'hygiene', '🪥'],
  ['deodorant', 'hygiene', '🧴'],
  ['rasoir', 'hygiene', '🪒'],
  ['mousse a raser', 'hygiene', '🧴'],
  ['coton', 'hygiene', '🧻'],
  ['papier toilette', 'hygiene', '🧻'],
  ['mouchoir', 'hygiene', '🤧'],
  ['serviette hygienique', 'hygiene', '🧴'],
  ['tampon', 'hygiene', '🧴'],
  ['creme solaire', 'hygiene', '🧴'],
  ['pansement', 'hygiene', '🩹'],
  ['medicament', 'hygiene', '💊'],

  // Entretien
  ['lessive', 'entretien', '🧺'],
  ['adoucissant', 'entretien', '🧺'],
  ['liquide vaisselle', 'entretien', '🧽'],
  ['eponge', 'entretien', '🧽'],
  ['nettoyant', 'entretien', '🧴'],
  ['javel', 'entretien', '🧴'],
  ['sac poubelle', 'entretien', '🗑️'],
  ['poubelle', 'entretien', '🗑️'],
  ['essuie-tout', 'entretien', '🧻'],
  ['sopalin', 'entretien', '🧻'],
  ['papier aluminium', 'entretien', '🧻'],
  ['film alimentaire', 'entretien', '🧻'],
  ['pile', 'entretien', '🔋'],
  ['ampoule', 'entretien', '💡'],
  ['allumette', 'entretien', '🔥'],
  ['bougie', 'entretien', '🕯️'],

  // Bébé
  ['couche', 'bebe', '🍼'],
  ['lingette', 'bebe', '🍼'],
  ['petit pot', 'bebe', '🍼'],
  ['biberon', 'bebe', '🍼'],
  ['lait infantile', 'bebe', '🍼'],

  // Animaux
  ['croquette', 'animaux', '🐾'],
  ['litiere', 'animaux', '🐾'],
  ['pature', 'animaux', '🐾'],
  ['chat', 'animaux', '🐱'],
  ['chien', 'animaux', '🐶'],
];
